name: Java Maven CI
# Este fluxo de trabalho é acionado em pushes para o repositório.
on: [push]

jobs:
  build:
    # nome do trabalho
    name: empacotar
    # Este trabalho executa no Linux.
    # A execução pode ser em uma máquina do Github, como neste caso, ou em uma máquina própria.
    # Mais info: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
    # abaixo está sendo citado um complemento disponível no Github que será utilizado.
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # disponibilizando arquivos para download
    - uses: actions/download-artifact@v1
      with:
        name: my-artifact
        path: target
